### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by dawolf82** [MichaelTaylor3D/gulp-cordova-bump#3]
I'm unable to get this installed on my Windows machine. Are there any system requirements prior to install? Thanks for contributing this. Here is what I get...
![issue](https://cloud.githubusercontent.com/assets/2486141/6361254/21bf064e-bc46-11e4-8ad6-04b001aae9af.PNG)

**Comment by MichaelTaylor3d** [comment]
Hmm, I get these types of errors on my mac when I dont use sudo. However windows doesnt have sudo. Something to try is maybe run the console as administrator? Also check your python PATH variable since I see that its mentioning that it cant find it. Ill do some tests in windows and see if I can duplicate.

Are you able to install other npm modules without this issue?

**Comment by dawolf82** [comment]
Thanks I figured it out. There were several issues including setting my python PATH. The issue is with the node-gyp installation.

If any other windows user experiences this issue here is what I did to fix it...

Make sure you have Microsoft Visual Studio C++ 2012/13 for Windows Desktop. The free express editions will work. I have 2013 Pro.
.
1. Installed Python 2.7 (doesn't like 3.x)
2. In my environment variables, I created a variable named "PYTHON" and set its path to point to the exe file. (In my case C:\Python27\python.exe)
3. Updated npm globally to the most recent version: npm install npm --g
4. npm install -g node-gyp --msvs_version=2013

Once I did all that it worked fine (you may see some warnings but it should still work).

Thanks Michael, this is a big help to my automated build process!

**Comment by jscti** [comment]
You should really consider not using node-gyp ... It's a pain to install all its dependencies.
Your plugin seems to do the job, unfortunately, I won't install it because of that.
